version: '3.8'

services:
  app:
    build:
      context: .  # Caminho para o diretório onde o Dockerfile está localizado
    container_name: springboot-app
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/duckfarm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=duckfarm
      - POSTGRES_USER=luiz
      - POSTGRES_PASSWORD=luiz-2024
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: